import type {
  Project, Contact, Company, List, Segment, Consent, Form, Activity, DashboardStats
} from './types'

// ─── Projects ─────────────────────────────────────────────────────────────────

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Dutch Market',
    slug: 'dutch-market',
    type: 'b2c',
    default_language: 'nl',
    default_country: 'NL',
    sending_domain: 'mail.dutchbrand.nl',
    privacy_notice_version: '2.1',
    is_active: true,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    contact_count: 4821,
    list_count: 8,
  },
  {
    id: 'proj-2',
    name: 'France',
    slug: 'france',
    type: 'b2c',
    default_language: 'fr',
    default_country: 'FR',
    sending_domain: 'mail.frenchbrand.fr',
    privacy_notice_version: '2.0',
    is_active: true,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    contact_count: 3204,
    list_count: 6,
  },
  {
    id: 'proj-3',
    name: 'Germany',
    slug: 'germany',
    type: 'b2c',
    default_language: 'de',
    default_country: 'DE',
    sending_domain: 'mail.germanbrand.de',
    privacy_notice_version: '2.2',
    is_active: true,
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    contact_count: 2890,
    list_count: 5,
  },
  {
    id: 'proj-4',
    name: 'Spain',
    slug: 'spain',
    type: 'b2c',
    default_language: 'es',
    default_country: 'ES',
    sending_domain: 'mail.spanishbrand.es',
    privacy_notice_version: '1.8',
    is_active: true,
    created_at: '2024-04-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    contact_count: 1950,
    list_count: 4,
  },
  {
    id: 'proj-5',
    name: 'Italy',
    slug: 'italy',
    type: 'b2c',
    default_language: 'it',
    default_country: 'IT',
    sending_domain: 'mail.italianbrand.it',
    privacy_notice_version: '1.5',
    is_active: false,
    created_at: '2024-04-15T10:00:00Z',
    updated_at: '2024-05-01T10:00:00Z',
    contact_count: 876,
    list_count: 3,
  },
]

// ─── Contacts ─────────────────────────────────────────────────────────────────

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'con-1',
    email: 'emma.janssen@gmail.com',
    email_normalized: 'emma.janssen@gmail.com',
    first_name: 'Emma',
    last_name: 'Janssen',
    phone: '+31 6 12345678',
    country_code: 'NL',
    residency_country: 'NL',
    preferred_language: 'nl',
    timezone: 'Europe/Amsterdam',
    currency: 'EUR',
    market: 'NL',
    lifecycle_stage: 'customer',
    source: 'organic_search',
    owner_id: null,
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-06-10T10:00:00Z',
  },
  {
    id: 'con-2',
    email: 'pierre.martin@free.fr',
    email_normalized: 'pierre.martin@free.fr',
    first_name: 'Pierre',
    last_name: 'Martin',
    phone: '+33 6 12345678',
    country_code: 'FR',
    residency_country: 'FR',
    preferred_language: 'fr',
    timezone: 'Europe/Paris',
    currency: 'EUR',
    market: 'FR',
    lifecycle_stage: 'prospect',
    source: 'paid_search',
    owner_id: null,
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'con-3',
    email: 'anna.schmidt@gmail.de',
    email_normalized: 'anna.schmidt@gmail.de',
    first_name: 'Anna',
    last_name: 'Schmidt',
    phone: '+49 151 12345678',
    country_code: 'DE',
    residency_country: 'DE',
    preferred_language: 'de',
    timezone: 'Europe/Berlin',
    currency: 'EUR',
    market: 'DE',
    lifecycle_stage: 'lead',
    source: 'form',
    owner_id: null,
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-05-20T10:00:00Z',
  },
  {
    id: 'con-4',
    email: 'carlos.garcia@outlook.es',
    email_normalized: 'carlos.garcia@outlook.es',
    first_name: 'Carlos',
    last_name: 'García',
    phone: '+34 612 345 678',
    country_code: 'ES',
    residency_country: 'ES',
    preferred_language: 'es',
    timezone: 'Europe/Madrid',
    currency: 'EUR',
    market: 'ES',
    lifecycle_stage: 'customer',
    source: 'social_media',
    owner_id: null,
    created_at: '2024-03-25T10:00:00Z',
    updated_at: '2024-06-05T10:00:00Z',
  },
  {
    id: 'con-5',
    email: 'giulia.ferrari@libero.it',
    email_normalized: 'giulia.ferrari@libero.it',
    first_name: 'Giulia',
    last_name: 'Ferrari',
    phone: '+39 333 1234567',
    country_code: 'IT',
    residency_country: 'IT',
    preferred_language: 'it',
    timezone: 'Europe/Rome',
    currency: 'EUR',
    market: 'IT',
    lifecycle_stage: 'evangelist',
    source: 'referral',
    owner_id: null,
    created_at: '2024-04-01T10:00:00Z',
    updated_at: '2024-06-08T10:00:00Z',
  },
  {
    id: 'con-6',
    email: 'lars.de.vries@xs4all.nl',
    email_normalized: 'lars.de.vries@xs4all.nl',
    first_name: 'Lars',
    last_name: 'de Vries',
    phone: '+31 6 87654321',
    country_code: 'NL',
    residency_country: 'NL',
    preferred_language: 'nl',
    timezone: 'Europe/Amsterdam',
    currency: 'EUR',
    market: 'NL',
    lifecycle_stage: 'churned',
    source: 'email_campaign',
    owner_id: null,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-04-15T10:00:00Z',
  },
  {
    id: 'con-7',
    email: 'sophie.lambert@gmail.com',
    email_normalized: 'sophie.lambert@gmail.com',
    first_name: 'Sophie',
    last_name: 'Lambert',
    phone: null,
    country_code: 'FR',
    residency_country: 'FR',
    preferred_language: 'fr',
    timezone: 'Europe/Paris',
    currency: 'EUR',
    market: 'FR',
    lifecycle_stage: 'lead',
    source: 'event',
    owner_id: null,
    created_at: '2024-05-10T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'con-8',
    email: 'max.müller@web.de',
    email_normalized: 'max.müller@web.de',
    first_name: 'Max',
    last_name: 'Müller',
    phone: '+49 170 1234567',
    country_code: 'DE',
    residency_country: 'DE',
    preferred_language: 'de',
    timezone: 'Europe/Berlin',
    currency: 'EUR',
    market: 'DE',
    lifecycle_stage: 'prospect',
    source: 'partner',
    owner_id: null,
    created_at: '2024-04-20T10:00:00Z',
    updated_at: '2024-06-02T10:00:00Z',
  },
]

// ─── Companies ────────────────────────────────────────────────────────────────

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'Janssen & Partners BV',
    domain: 'janssen-partners.nl',
    registered_country: 'NL',
    billing_country: 'NL',
    vat_number: 'NL123456789B01',
    vat_validated_at: '2024-01-15T10:00:00Z',
    industry: 'Professional Services',
    company_size: '11-50',
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    contact_count: 3,
  },
  {
    id: 'comp-2',
    name: 'Martin Conseil SAS',
    domain: 'martin-conseil.fr',
    registered_country: 'FR',
    billing_country: 'FR',
    vat_number: 'FR12345678901',
    vat_validated_at: '2024-02-01T10:00:00Z',
    industry: 'Financial Services',
    company_size: '51-200',
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-05-20T10:00:00Z',
    contact_count: 5,
  },
  {
    id: 'comp-3',
    name: 'Schmidt GmbH',
    domain: 'schmidt-gmbh.de',
    registered_country: 'DE',
    billing_country: 'DE',
    vat_number: 'DE123456789',
    vat_validated_at: null,
    industry: 'Manufacturing',
    company_size: '201-500',
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-06-05T10:00:00Z',
    contact_count: 8,
  },
  {
    id: 'comp-4',
    name: 'García & Asociados SL',
    domain: 'garcia-asociados.es',
    registered_country: 'ES',
    billing_country: 'ES',
    vat_number: 'ESB12345678',
    vat_validated_at: '2024-04-01T10:00:00Z',
    industry: 'Retail & E-commerce',
    company_size: '11-50',
    created_at: '2024-04-01T10:00:00Z',
    updated_at: '2024-05-15T10:00:00Z',
    contact_count: 2,
  },
  {
    id: 'comp-5',
    name: 'Ferrari Design SRL',
    domain: 'ferrari-design.it',
    registered_country: 'IT',
    billing_country: 'IT',
    vat_number: 'IT12345678901',
    vat_validated_at: '2024-04-15T10:00:00Z',
    industry: 'Advertising & Marketing',
    company_size: '1-10',
    created_at: '2024-04-15T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    contact_count: 1,
  },
]

// ─── Lists ────────────────────────────────────────────────────────────────────

export const MOCK_LISTS: List[] = [
  {
    id: 'list-1',
    project_id: 'proj-1',
    name: 'Newsletter NL',
    description: 'Dutch language newsletter subscribers',
    is_active: true,
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    contact_count: 3210,
    project: MOCK_PROJECTS[0],
  },
  {
    id: 'list-2',
    project_id: 'proj-1',
    name: 'Promo NL',
    description: 'Opted in to promotional emails',
    is_active: true,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    contact_count: 1850,
    project: MOCK_PROJECTS[0],
  },
  {
    id: 'list-3',
    project_id: 'proj-2',
    name: 'Newsletter FR',
    description: 'French language newsletter subscribers',
    is_active: true,
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    contact_count: 2100,
    project: MOCK_PROJECTS[1],
  },
  {
    id: 'list-4',
    project_id: 'proj-3',
    name: 'Newsletter DE',
    description: 'German language newsletter subscribers',
    is_active: true,
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    contact_count: 1980,
    project: MOCK_PROJECTS[2],
  },
  {
    id: 'list-5',
    project_id: 'proj-4',
    name: 'Newsletter ES',
    description: 'Spanish language newsletter subscribers',
    is_active: true,
    created_at: '2024-04-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    contact_count: 1400,
    project: MOCK_PROJECTS[3],
  },
]

// ─── Segments ─────────────────────────────────────────────────────────────────

export const MOCK_SEGMENTS: Segment[] = [
  {
    id: 'seg-1',
    project_id: 'proj-1',
    name: 'Active NL Customers',
    description: 'Customers in Netherlands who are active',
    conditions: [
      { field: 'lifecycle_stage', operator: 'equals', value: 'customer' },
      { field: 'residency_country', operator: 'equals', value: 'NL' },
    ],
    is_active: true,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    contact_count: 1240,
    project: MOCK_PROJECTS[0],
  },
  {
    id: 'seg-2',
    project_id: 'proj-2',
    name: 'French Prospects',
    description: 'Prospects in France',
    conditions: [
      { field: 'lifecycle_stage', operator: 'equals', value: 'prospect' },
      { field: 'residency_country', operator: 'equals', value: 'FR' },
    ],
    is_active: true,
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    contact_count: 480,
    project: MOCK_PROJECTS[1],
  },
  {
    id: 'seg-3',
    project_id: 'proj-1',
    name: 'At-Risk (NL)',
    description: 'Customers who haven\'t engaged in 90 days',
    conditions: [
      { field: 'lifecycle_stage', operator: 'equals', value: 'customer' },
      { field: 'residency_country', operator: 'equals', value: 'NL' },
    ],
    is_active: true,
    created_at: '2024-04-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    contact_count: 312,
    project: MOCK_PROJECTS[0],
  },
]

// ─── Consents ─────────────────────────────────────────────────────────────────

export const MOCK_CONSENTS: Consent[] = [
  {
    id: 'cns-1',
    contact_id: 'con-1',
    project_id: 'proj-1',
    list_id: 'list-1',
    channel: 'email',
    purpose: 'newsletter',
    consent_status: 'opted_in',
    legal_basis: 'consent',
    consent_country: 'NL',
    consent_language: 'nl',
    consent_text_version: '1.2',
    privacy_notice_version: '2.1',
    source_form_id: null,
    source_page: '/nl/inschrijven',
    consented_at: '2024-01-20T10:00:00Z',
    withdrawn_at: null,
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-01-20T10:00:00Z',
    contact: MOCK_CONTACTS[0],
    project: MOCK_PROJECTS[0],
  },
  {
    id: 'cns-2',
    contact_id: 'con-2',
    project_id: 'proj-2',
    list_id: 'list-3',
    channel: 'email',
    purpose: 'newsletter',
    consent_status: 'opted_in',
    legal_basis: 'consent',
    consent_country: 'FR',
    consent_language: 'fr',
    consent_text_version: '1.0',
    privacy_notice_version: '2.0',
    source_form_id: null,
    source_page: '/fr/inscription',
    consented_at: '2024-02-15T10:00:00Z',
    withdrawn_at: null,
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-02-15T10:00:00Z',
    contact: MOCK_CONTACTS[1],
    project: MOCK_PROJECTS[1],
  },
  {
    id: 'cns-3',
    contact_id: 'con-6',
    project_id: 'proj-1',
    list_id: 'list-1',
    channel: 'email',
    purpose: 'newsletter',
    consent_status: 'unsubscribed',
    legal_basis: 'consent',
    consent_country: 'NL',
    consent_language: 'nl',
    consent_text_version: '1.0',
    privacy_notice_version: '2.0',
    source_form_id: null,
    source_page: '/nl/inschrijven',
    consented_at: '2024-02-01T10:00:00Z',
    withdrawn_at: '2024-04-10T10:00:00Z',
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-04-10T10:00:00Z',
    contact: MOCK_CONTACTS[5],
    project: MOCK_PROJECTS[0],
  },
]

// ─── Forms ────────────────────────────────────────────────────────────────────

export const MOCK_FORMS: Form[] = [
  {
    id: 'form-1',
    project_id: 'proj-1',
    name: 'NL Newsletter Signup',
    slug: 'nl-newsletter',
    fields: [
      { id: 'f1', type: 'email', label: 'E-mailadres', name: 'email', required: true, maps_to: 'email' },
      { id: 'f2', type: 'text', label: 'Voornaam', name: 'first_name', required: false, maps_to: 'first_name' },
      { id: 'f3', type: 'checkbox', label: 'Ik ga akkoord met de privacy verklaring', name: 'consent', required: true },
    ],
    settings: { redirect_url: '/nl/bedankt', send_confirmation: true },
    is_active: true,
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    submission_count: 4821,
    project: MOCK_PROJECTS[0],
  },
  {
    id: 'form-2',
    project_id: 'proj-2',
    name: 'FR Newsletter Signup',
    slug: 'fr-newsletter',
    fields: [
      { id: 'f1', type: 'email', label: 'Adresse e-mail', name: 'email', required: true, maps_to: 'email' },
      { id: 'f2', type: 'text', label: 'Prénom', name: 'first_name', required: false, maps_to: 'first_name' },
      { id: 'f3', type: 'checkbox', label: 'J\'accepte la politique de confidentialité', name: 'consent', required: true },
    ],
    settings: { redirect_url: '/fr/merci', send_confirmation: true },
    is_active: true,
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    submission_count: 3204,
    project: MOCK_PROJECTS[1],
  },
]

// ─── Activities ───────────────────────────────────────────────────────────────

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    contact_id: 'con-1',
    company_id: null,
    project_id: 'proj-1',
    type: 'form_submitted',
    subject: 'NL Newsletter Signup',
    body: null,
    metadata: { form_id: 'form-1' },
    performed_by: null,
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 'act-2',
    contact_id: 'con-1',
    company_id: null,
    project_id: 'proj-1',
    type: 'list_added',
    subject: 'Added to Newsletter NL',
    body: null,
    metadata: { list_id: 'list-1' },
    performed_by: null,
    created_at: '2024-01-20T10:05:00Z',
  },
  {
    id: 'act-3',
    contact_id: 'con-2',
    company_id: null,
    project_id: 'proj-2',
    type: 'form_submitted',
    subject: 'FR Newsletter Signup',
    body: null,
    metadata: { form_id: 'form-2' },
    performed_by: null,
    created_at: '2024-02-15T10:00:00Z',
  },
]

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  total_contacts: 13741,
  contacts_by_project: [
    { project: 'Dutch Market', count: 4821 },
    { project: 'France', count: 3204 },
    { project: 'Germany', count: 2890 },
    { project: 'Spain', count: 1950 },
    { project: 'Italy', count: 876 },
  ],
  contacts_by_country: [
    { country: 'NL', count: 4821 },
    { country: 'FR', count: 3204 },
    { country: 'DE', count: 2890 },
    { country: 'ES', count: 1950 },
    { country: 'IT', count: 876 },
  ],
  contacts_by_lifecycle: [
    { stage: 'lead', count: 3120 },
    { stage: 'prospect', count: 4250 },
    { stage: 'customer', count: 5180 },
    { stage: 'evangelist', count: 840 },
    { stage: 'churned', count: 351 },
  ],
  new_contacts_over_time: [
    { date: '2024-01', count: 820 },
    { date: '2024-02', count: 1100 },
    { date: '2024-03', count: 980 },
    { date: '2024-04', count: 1350 },
    { date: '2024-05', count: 1540 },
    { date: '2024-06', count: 1210 },
  ],
  list_growth: [
    { list: 'Newsletter NL', count: 3210 },
    { list: 'Promo NL', count: 1850 },
    { list: 'Newsletter FR', count: 2100 },
    { list: 'Newsletter DE', count: 1980 },
    { list: 'Newsletter ES', count: 1400 },
  ],
  consent_summary: [
    { status: 'opted_in', count: 10820 },
    { status: 'pending', count: 1540 },
    { status: 'opted_out', count: 890 },
    { status: 'unsubscribed', count: 491 },
  ],
}
